- name: Create LTM TCP monitors
  f5networks.f5_modules.bigip_monitor_tcp:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    parent: "{{ item.parent | default(omit) }}"
    send: "{{ item.send | default(omit) }}"
    receive: "{{ item.receive | default(omit) }}"
    interval: "{{ item.interval | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    transparent: "{{ item.transparent | default(omit) }}"
    reverse: "{{ item.reverse | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ltm_monitors_present | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == 'tcp'

- name: Create LTM HTTP monitors
  f5networks.f5_modules.bigip_monitor_http:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    parent: "{{ item.parent | default(omit) }}"
    send: "{{ item.send | default(omit) }}"
    receive: "{{ item.receive | default(omit) }}"
    interval: "{{ item.interval | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    transparent: "{{ item.transparent | default(omit) }}"
    reverse: "{{ item.reverse | default(omit) }}"
    ip: "{{ item.ip | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ltm_monitors_present | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == 'http'

- name: Create LTM HTTPS monitors
  f5networks.f5_modules.bigip_monitor_https:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    parent: "{{ item.parent | default(omit) }}"
    send: "{{ item.send | default(omit) }}"
    receive: "{{ item.receive | default(omit) }}"
    interval: "{{ item.interval | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    transparent: "{{ item.transparent | default(omit) }}"
    reverse: "{{ item.reverse | default(omit) }}"
    ip: "{{ item.ip | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    cipher_list: "{{ item.cipher_list | default(omit) }}"
    compatibility: "{{ item.compatibility | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ltm_monitors_present | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == 'https'

- name: Create LTM gateway ICMP monitors
  f5networks.f5_modules.bigip_monitor_gateway_icmp:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    parent: "{{ item.parent | default(omit) }}"
    interval: "{{ item.interval | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    ip: "{{ item.ip | default(omit) }}"
    transparent: "{{ item.transparent | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ltm_monitors_present | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.type == 'gateway_icmp'

- name: Create LTM nodes
  f5networks.f5_modules.bigip_node:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    address: "{{ item.address | default(omit) }}"
    fqdn: "{{ item.fqdn | default(omit) }}"
    fqdn_address_type: "{{ item.fqdn_address_type | default(omit) }}"
    fqdn_auto_populate: "{{ item.fqdn_auto_populate | default(omit) }}"
    fqdn_down_interval: "{{ item.fqdn_down_interval | default(omit) }}"
    fqdn_up_interval: "{{ item.fqdn_up_interval | default(omit) }}"
    monitors: "{{ item.monitors | default(omit) }}"
    availability_requirements: "{{ item.availability_requirements | default(omit) }}"
    connection_limit: "{{ item.connection_limit | default(omit) }}"
    description: "{{ item.description | default(omit) }}"
    dynamic_ratio: "{{ item.dynamic_ratio | default(omit) }}"
    rate_limit: "{{ item.rate_limit | default(omit) }}"
    ratio: "{{ item.ratio | default(omit) }}"
    state: "{{ item.state | default((item.enabled | default(true)) | ternary('enabled', 'disabled')) }}"
  loop: "{{ ltm_nodes_present | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Create LTM pools
  f5networks.f5_modules.bigip_pool:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    lb_method: "{{ item.lb_method | default('round-robin') }}"
    monitors: "{{ item.monitors | default(omit) }}"
    monitor_type: "{{ item.monitor_type | default(omit) }}"
    quorum: "{{ item.quorum | default(omit) }}"
    metadata: "{{ item.metadata | default(omit) }}"
    min_up_members: "{{ item.min_up_members | default(omit) }}"
    min_up_members_action: "{{ item.min_up_members_action | default(omit) }}"
    min_up_members_checking: "{{ item.min_up_members_checking | default(omit) }}"
    priority_group_activation: "{{ item.priority_group_activation | default(omit) }}"
    reselect_tries: "{{ item.reselect_tries | default(omit) }}"
    service_down_action: "{{ item.service_down_action | default(omit) }}"
    slow_ramp_time: "{{ item.slow_ramp_time | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ ltm_all_pools_present | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Add members to pools
  f5networks.f5_modules.bigip_pool_member:
    provider: "{{ provider }}"
    partition: "{{ item.0.partition | default('Common') }}"
    pool: "{{ item.0.name }}"
    name: "{{ item.1.name | default(omit) }}"
    host: "{{ item.1.host | default(item.1.address | default(omit)) }}"
    fqdn: "{{ item.1.fqdn | default(omit) }}"
    fqdn_auto_populate: "{{ item.1.fqdn_auto_populate | default(omit) }}"
    port: "{{ item.1.port }}"
    monitors: "{{ item.1.monitors | default(omit) }}"
    availability_requirements: "{{ item.1.availability_requirements | default(omit) }}"
    connection_limit: "{{ item.1.connection_limit | default(omit) }}"
    description: "{{ item.1.description | default(omit) }}"
    ip_encapsulation: "{{ item.1.ip_encapsulation | default(omit) }}"
    preserve_node: "{{ item.1.preserve_node | default(omit) }}"
    priority_group: "{{ item.1.priority_group | default(omit) }}"
    rate_limit: "{{ item.1.rate_limit | default(omit) }}"
    ratio: "{{ item.1.ratio | default(omit) }}"
    reuse_nodes: "{{ item.1.reuse_nodes | default(omit) }}"
    state: "{{ item.1.state | default((item.1.enabled | default(true)) | ternary('enabled', 'disabled')) }}"
  loop: "{{ query('subelements', ltm_all_pools_present | default([]), 'members', {'skip_missing': True}) }}"
  loop_control:
    label: "{{ item.0.partition | default('Common') }}/{{ item.0.name }}:{{ item.1.name | default(item.1.host | default(item.1.address | default(item.1.fqdn | default('member')))) }}:{{ item.1.port }}"

- name: Create virtual servers
  f5networks.f5_modules.bigip_virtual_server:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    destination: "{{ item.destination }}"
    port: "{{ item.destination_port }}"
    pool: "{{ item.pool.name if item.pool is mapping else item.pool }}"
    snat: "{{ item.snat | default('Automap') }}"
    all_profiles: "{{ item.profiles | default(['tcp']) }}"
    description: "{{ item.description | default(omit) }}"
    state: "{{ item.state | default((item.enabled | default(true)) | ternary('enabled', 'disabled')) }}"
  loop: "{{ ltm_virtual_servers_present | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
