- name: Delete virtual servers
  f5networks.f5_modules.bigip_virtual_server:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_virtual_servers_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Delete LTM TCP profiles
  f5networks.f5_modules.bigip_profile_tcp:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'tcp'

- name: Delete LTM UDP profiles
  f5networks.f5_modules.bigip_profile_udp:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'udp'

- name: Delete LTM fastL4 profiles
  f5networks.f5_modules.bigip_profile_fastl4:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'fastl4'

- name: Delete LTM HTTP profiles
  f5networks.f5_modules.bigip_profile_http:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'http'

- name: Delete LTM HTTP/2 profiles
  f5networks.f5_modules.bigip_profile_http2:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'http2'

- name: Delete LTM OneConnect profiles
  f5networks.f5_modules.bigip_profile_oneconnect:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'oneconnect'

- name: Delete pools
  f5networks.f5_modules.bigip_pool:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_all_pools_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Delete nodes
  f5networks.f5_modules.bigip_node:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_nodes_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Delete LTM TCP monitors
  f5networks.f5_modules.bigip_monitor_tcp:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_monitors_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'tcp'

- name: Delete LTM HTTP monitors
  f5networks.f5_modules.bigip_monitor_http:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_monitors_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'http'

- name: Delete LTM HTTPS monitors
  f5networks.f5_modules.bigip_monitor_https:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_monitors_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'https'

- name: Delete LTM policies
  f5networks.f5_modules.bigip_policy:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_policies_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Delete iRules
  f5networks.f5_modules.bigip_irule:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_irules_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Delete LTM cookie persistence profiles
  f5networks.f5_modules.bigip_profile_persistence_cookie:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_persistence_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'cookie'

- name: Delete LTM source address persistence profiles
  f5networks.f5_modules.bigip_profile_persistence_src_addr:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_persistence_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'source_addr'

- name: Delete LTM universal persistence profiles
  f5networks.f5_modules.bigip_profile_persistence_universal:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_persistence_profiles_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'universal'

- name: Delete data groups
  f5networks.f5_modules.bigip_data_group:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_data_groups_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Delete LTM gateway ICMP monitors
  f5networks.f5_modules.bigip_monitor_gateway_icmp:
    provider: "{{ provider }}"
    partition: "{{ item.partition | default('Common') }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ ltm_monitors_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"
  when: item.type == 'gateway_icmp'
