---
ltm_pools:
  - name: "pool_inventory_east_8443"
    description: "East region inventory application pool"
    lb_method: "least-connections-member"
    monitors:
      - "standard_https"
    members:
      - name: "inventory-east-1"
        host: "10.201.40.11"
        port: 8443
      - name: "inventory-east-2"
        host: "10.201.40.12"
        port: 8443

  - name: "pool_inventory_west_8443"
    description: "West region inventory application pool"
    lb_method: "least-connections-member"
    monitors:
      - "standard_https"
    members:
      - name: "inventory-west-1"
        host: "10.202.40.11"
        port: 8443
      - name: "inventory-west-2"
        host: "10.202.40.12"
        port: 8443

  - name: "pool_reporting_east_8443"
    description: "East region reporting application pool"
    lb_method: "least-connections-member"
    monitors:
      - "standard_https"
    members:
      - name: "reporting-east-1"
        host: "10.201.41.11"
        port: 8443
      - name: "reporting-east-2"
        host: "10.201.41.12"
        port: 8443

  - name: "pool_reporting_west_8443"
    description: "West region reporting application pool"
    lb_method: "least-connections-member"
    monitors:
      - "standard_https"
    members:
      - name: "reporting-west-1"
        host: "10.202.41.11"
        port: 8443
      - name: "reporting-west-2"
        host: "10.202.41.12"
        port: 8443
