- name: Discover LTM RKE2 server intent fragments
  ansible.builtin.set_fact:
    ltm_rke2_server_intent_files: "{{ (repo_root ~ '/vars/ltm/intents/clusters') | discover_yaml_fragments }}"
    ltm_rke2_server_intent_deletion_files: "{{ (repo_root ~ '/vars/ltm/deletions/intents/clusters') | discover_yaml_fragments }}"

- name: Load LTM RKE2 server intent fragments
  ansible.builtin.include_vars:
    file: "{{ item }}"
    name: ltm_rke2_server_intent_fragment
  loop: "{{ ltm_rke2_server_intent_files }}"
  register: ltm_rke2_server_intent_include_results

- name: Load LTM RKE2 server intent deletion fragments
  ansible.builtin.include_vars:
    file: "{{ item }}"
    name: ltm_rke2_server_intent_deletion_fragment
  loop: "{{ ltm_rke2_server_intent_deletion_files }}"
  register: ltm_rke2_server_intent_deletion_include_results

- name: Aggregate LTM RKE2 server intents with layered directory settings
  ansible.builtin.set_fact:
    ltm_rke2_server_intents: >-
      {{
        ltm_rke2_server_intents | default([]) + [
          (
            ltm_rke2_server_intent_settings_payload.ltm_rke2_server_intent_defaults
            | default({})
            | combine(item.1, recursive=True)
            | combine({'__source_file': item.0.item}, recursive=True)
          )
        ]
      }}
  loop: "{{ query('subelements', ltm_rke2_server_intent_include_results.results, 'ansible_facts.ltm_rke2_server_intent_fragment.ltm_rke2_server_intents', {'skip_missing': True}) }}"
  vars:
    ltm_rke2_server_intent_settings_payload: >-
      {{
        item.0.item
        | load_settings_hierarchy(repo_root ~ '/vars/ltm/intents')
      }}

- name: Aggregate LTM RKE2 server intent deletions with layered directory settings
  ansible.builtin.set_fact:
    ltm_rke2_server_intent_deletions: >-
      {{
        ltm_rke2_server_intent_deletions | default([]) + [
          (
            (
              ltm_rke2_server_intent_deletion_settings_payload.ltm_rke2_server_intent_defaults
              | default({})
              | combine(item.1, recursive=True)
              | combine({'state': 'absent'}, recursive=True)
            )
            | combine({'__source_file': item.0.item}, recursive=True)
          )
        ]
      }}
  loop: "{{ query('subelements', ltm_rke2_server_intent_deletion_include_results.results, 'ansible_facts.ltm_rke2_server_intent_deletion_fragment.ltm_rke2_server_intents', {'skip_missing': True}) }}"
  vars:
    ltm_rke2_server_intent_deletion_settings_payload: >-
      {{
        item.0.item
        | load_settings_hierarchy(repo_root ~ '/vars/ltm/deletions/intents')
      }}
