---
bigip_static_routes:
  - name: "default-inet"
    destination: "0.0.0.0"
    netmask: "0.0.0.0"
    gateway_address: "10.10.11.1"
    description: "Default route for the shared route domain"

  - name: "tenant-a-default"
    destination: "0.0.0.0"
    netmask: "0.0.0.0"
    gateway_address: "10.10.21.1"
    route_domain: 100
    vlan: "internal"
    description: "Default route inside tenant A"
