---
enable_gtm: false

gtm_mirror_pair:
  datacenter: "dc-east"
  wide_ip: "grafana.my.domain.com"
  pool_name: "pool_grafana_ab"
  members:
    - cluster: "a"
      gtm_server: "gtm-ltm-cluster-a"
      gtm_server_ip: "192.0.2.10"
      virtual_server: "gtm_vs_a_grafana_443"
      address: "10.10.11.102"
      port: 443
      monitors:
        - "/Common/https"
    - cluster: "b"
      gtm_server: "gtm-ltm-cluster-b"
      gtm_server_ip: "192.0.2.11"
      virtual_server: "gtm_vs_b_grafana_443"
      address: "10.10.12.102"
      port: 443
      monitors:
        - "/Common/https"
