from __future__ import annotations

from .constants import VARS_DIR
from .models import TreeSpec


def build_tree_specs() -> list[TreeSpec]:
    return [
        TreeSpec(
            name="bootstrap_licenses",
            active_dir=VARS_DIR / "bootstrap" / "license",
            deletion_dir=VARS_DIR / "bootstrap" / "deletions" / "license",
            top_key="bootstrap_licenses",
            settings_key="bootstrap_license_defaults",
        ),
        TreeSpec(
            name="bootstrap_management",
            active_dir=VARS_DIR / "bootstrap" / "management",
            deletion_dir=VARS_DIR / "bootstrap" / "deletions" / "management",
            top_key="bootstrap_management",
            settings_key="bootstrap_management_defaults",
        ),
        TreeSpec(
            name="ha_device_trusts",
            active_dir=VARS_DIR / "ha" / "device_trust",
            deletion_dir=VARS_DIR / "ha" / "deletions" / "device_trust",
            top_key="ha_device_trusts",
            settings_key="ha_device_trust_defaults",
        ),
        TreeSpec(
            name="ha_device_groups",
            active_dir=VARS_DIR / "ha" / "device_groups",
            deletion_dir=VARS_DIR / "ha" / "deletions" / "device_groups",
            top_key="ha_device_groups",
            settings_key="ha_device_group_defaults",
        ),
        TreeSpec(
            name="ha_device_group_members",
            active_dir=VARS_DIR / "ha" / "device_group_members",
            deletion_dir=VARS_DIR / "ha" / "deletions" / "device_group_members",
            top_key="ha_device_group_members",
            settings_key="ha_device_group_member_defaults",
        ),
        TreeSpec(
            name="ha_traffic_groups",
            active_dir=VARS_DIR / "ha" / "traffic_groups",
            deletion_dir=VARS_DIR / "ha" / "deletions" / "traffic_groups",
            top_key="ha_traffic_groups",
            settings_key="ha_traffic_group_defaults",
        ),
        TreeSpec(
            name="ha_device_connectivity",
            active_dir=VARS_DIR / "ha" / "device_connectivity",
            deletion_dir=VARS_DIR / "ha" / "deletions" / "device_connectivity",
            top_key="ha_device_connectivity",
            settings_key="ha_device_connectivity_defaults",
        ),
        TreeSpec(
            name="ha_groups",
            active_dir=VARS_DIR / "ha" / "ha_groups",
            deletion_dir=VARS_DIR / "ha" / "deletions" / "ha_groups",
            top_key="ha_groups",
            settings_key="ha_group_defaults",
        ),
        TreeSpec(
            name="ha_configsync_actions",
            active_dir=VARS_DIR / "ha" / "configsync_actions",
            deletion_dir=VARS_DIR / "ha" / "deletions" / "configsync_actions",
            top_key="ha_configsync_actions",
            settings_key="ha_configsync_action_defaults",
        ),
        TreeSpec(
            name="tls_keys",
            active_dir=VARS_DIR / "tls" / "keys",
            deletion_dir=VARS_DIR / "tls" / "deletions" / "keys",
            top_key="tls_keys",
            settings_key="tls_key_defaults",
        ),
        TreeSpec(
            name="tls_certificates",
            active_dir=VARS_DIR / "tls" / "certificates",
            deletion_dir=VARS_DIR / "tls" / "deletions" / "certificates",
            top_key="tls_certificates",
            settings_key="tls_certificate_defaults",
        ),
        TreeSpec(
            name="tls_ca_bundles",
            active_dir=VARS_DIR / "tls" / "ca_bundles",
            deletion_dir=VARS_DIR / "tls" / "deletions" / "ca_bundles",
            top_key="tls_ca_bundles",
            settings_key="tls_ca_bundle_defaults",
        ),
        TreeSpec(
            name="tls_client_ssl_profiles",
            active_dir=VARS_DIR / "tls" / "client_ssl_profiles",
            deletion_dir=VARS_DIR / "tls" / "deletions" / "client_ssl_profiles",
            top_key="tls_client_ssl_profiles",
            settings_key="tls_client_ssl_profile_defaults",
        ),
        TreeSpec(
            name="tls_server_ssl_profiles",
            active_dir=VARS_DIR / "tls" / "server_ssl_profiles",
            deletion_dir=VARS_DIR / "tls" / "deletions" / "server_ssl_profiles",
            top_key="tls_server_ssl_profiles",
            settings_key="tls_server_ssl_profile_defaults",
        ),
        TreeSpec(
            name="network_vlans",
            active_dir=VARS_DIR / "network" / "vlans",
            deletion_dir=VARS_DIR / "network" / "deletions" / "vlans",
            top_key="bigip_vlans",
            settings_key="network_vlan_defaults",
        ),
        TreeSpec(
            name="network_self_ips",
            active_dir=VARS_DIR / "network" / "self_ips",
            deletion_dir=VARS_DIR / "network" / "deletions" / "self_ips",
            top_key="bigip_self_ips",
            settings_key="network_self_ip_defaults",
        ),
        TreeSpec(
            name="network_route_domains",
            active_dir=VARS_DIR / "network" / "route_domains",
            deletion_dir=VARS_DIR / "network" / "deletions" / "route_domains",
            top_key="bigip_route_domains",
            settings_key="network_route_domain_defaults",
        ),
        TreeSpec(
            name="network_routes",
            active_dir=VARS_DIR / "network" / "routes",
            deletion_dir=VARS_DIR / "network" / "deletions" / "routes",
            top_key="bigip_static_routes",
            settings_key="network_route_defaults",
        ),
        TreeSpec(
            name="network_snat_translations",
            active_dir=VARS_DIR / "network" / "snat_translations",
            deletion_dir=VARS_DIR / "network" / "deletions" / "snat_translations",
            top_key="bigip_snat_translations",
            settings_key="network_snat_translation_defaults",
        ),
        TreeSpec(
            name="network_snat_pools",
            active_dir=VARS_DIR / "network" / "snats",
            deletion_dir=VARS_DIR / "network" / "deletions" / "snats",
            top_key="bigip_snat_pools",
            settings_key="network_snat_pool_defaults",
        ),
        TreeSpec(
            name="network_trunks",
            active_dir=VARS_DIR / "network" / "trunks",
            deletion_dir=VARS_DIR / "network" / "deletions" / "trunks",
            top_key="bigip_trunks",
            settings_key="network_trunk_defaults",
        ),
        TreeSpec(
            name="network_nats",
            active_dir=VARS_DIR / "network" / "nats",
            deletion_dir=VARS_DIR / "network" / "deletions" / "nats",
            top_key="bigip_nats",
            settings_key="network_nat_defaults",
        ),
        TreeSpec(
            name="system_hostnames",
            active_dir=VARS_DIR / "system" / "hostname",
            deletion_dir=VARS_DIR / "system" / "deletions" / "hostname",
            top_key="system_hostnames",
            settings_key="system_hostname_defaults",
        ),
        TreeSpec(
            name="system_dns",
            active_dir=VARS_DIR / "system" / "dns",
            deletion_dir=VARS_DIR / "system" / "deletions" / "dns",
            top_key="system_dns",
            settings_key="system_dns_defaults",
        ),
        TreeSpec(
            name="system_ntp",
            active_dir=VARS_DIR / "system" / "ntp",
            deletion_dir=VARS_DIR / "system" / "deletions" / "ntp",
            top_key="system_ntp",
            settings_key="system_ntp_defaults",
        ),
        TreeSpec(
            name="system_provisioning",
            active_dir=VARS_DIR / "system" / "provisioning",
            deletion_dir=VARS_DIR / "system" / "deletions" / "provisioning",
            top_key="system_provisioning",
            settings_key="system_provisioning_defaults",
        ),
        TreeSpec(
            name="system_partitions",
            active_dir=VARS_DIR / "system" / "partitions",
            deletion_dir=VARS_DIR / "system" / "deletions" / "partitions",
            top_key="system_partitions",
            settings_key="system_partition_defaults",
        ),
        TreeSpec(
            name="system_users",
            active_dir=VARS_DIR / "system" / "users",
            deletion_dir=VARS_DIR / "system" / "deletions" / "users",
            top_key="system_users",
            settings_key="system_user_defaults",
        ),
        TreeSpec(
            name="system_auth_ldap",
            active_dir=VARS_DIR / "system" / "auth" / "ldap",
            deletion_dir=VARS_DIR / "system" / "deletions" / "auth" / "ldap",
            top_key="system_auth_ldap",
            settings_key="system_auth_ldap_defaults",
        ),
        TreeSpec(
            name="system_auth_tacacs",
            active_dir=VARS_DIR / "system" / "auth" / "tacacs",
            deletion_dir=VARS_DIR / "system" / "deletions" / "auth" / "tacacs",
            top_key="system_auth_tacacs",
            settings_key="system_auth_tacacs_defaults",
        ),
        TreeSpec(
            name="system_auth_radius_servers",
            active_dir=VARS_DIR / "system" / "auth" / "radius_servers",
            deletion_dir=VARS_DIR / "system" / "deletions" / "auth" / "radius_servers",
            top_key="system_auth_radius_servers",
            settings_key="system_auth_radius_server_defaults",
        ),
        TreeSpec(
            name="system_auth_radius",
            active_dir=VARS_DIR / "system" / "auth" / "radius",
            deletion_dir=VARS_DIR / "system" / "deletions" / "auth" / "radius",
            top_key="system_auth_radius",
            settings_key="system_auth_radius_defaults",
        ),
        TreeSpec(
            name="system_auth_remote_roles",
            active_dir=VARS_DIR / "system" / "auth" / "remote_roles",
            deletion_dir=VARS_DIR / "system" / "deletions" / "auth" / "remote_roles",
            top_key="system_auth_remote_roles",
            settings_key="system_auth_remote_role_defaults",
        ),
        TreeSpec(
            name="system_login_banners",
            active_dir=VARS_DIR / "system" / "login_banners",
            deletion_dir=VARS_DIR / "system" / "deletions" / "login_banners",
            top_key="system_login_banners",
            settings_key="system_login_banner_defaults",
        ),
        TreeSpec(
            name="system_config",
            active_dir=VARS_DIR / "system" / "config",
            deletion_dir=VARS_DIR / "system" / "deletions" / "config",
            top_key="system_config",
            settings_key="system_config_defaults",
        ),
        TreeSpec(
            name="ltm_nodes",
            active_dir=VARS_DIR / "ltm" / "nodes",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "nodes",
            top_key="ltm_nodes",
            settings_key="ltm_node_defaults",
        ),
        TreeSpec(
            name="ltm_profiles",
            active_dir=VARS_DIR / "ltm" / "profiles",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "profiles",
            top_key="ltm_profiles",
            settings_key="ltm_profile_defaults",
        ),
        TreeSpec(
            name="ltm_pools",
            active_dir=VARS_DIR / "ltm" / "pools",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "pools",
            top_key="ltm_pools",
            settings_key="ltm_pool_defaults",
            extra_settings_keys=("ltm_member_defaults", "ltm_monitor_sets"),
        ),
        TreeSpec(
            name="ltm_monitors",
            active_dir=VARS_DIR / "ltm" / "monitors",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "monitors",
            top_key="ltm_monitors",
            settings_key="ltm_monitor_defaults",
        ),
        TreeSpec(
            name="ltm_virtual_servers",
            active_dir=VARS_DIR / "ltm" / "virtual_servers",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "virtual_servers",
            top_key="ltm_virtual_servers",
            settings_key="ltm_virtual_server_defaults",
        ),
        TreeSpec(
            name="ltm_inline_virtual_server_intents",
            active_dir=VARS_DIR / "ltm" / "intents" / "inline",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "intents" / "inline",
            top_key="ltm_inline_virtual_server_intents",
            settings_key="ltm_virtual_server_defaults",
            extra_settings_keys=("ltm_pool_defaults", "ltm_member_defaults", "ltm_monitor_sets"),
        ),
        TreeSpec(
            name="ltm_persistence_profiles",
            active_dir=VARS_DIR / "ltm" / "persistence",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "persistence",
            top_key="ltm_persistence_profiles",
            settings_key="ltm_persistence_profile_defaults",
        ),
        TreeSpec(
            name="ltm_irules",
            active_dir=VARS_DIR / "ltm" / "irules",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "irules",
            top_key="ltm_irules",
            settings_key="ltm_irule_defaults",
        ),
        TreeSpec(
            name="ltm_data_groups",
            active_dir=VARS_DIR / "ltm" / "data_groups",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "data_groups",
            top_key="ltm_data_groups",
            settings_key="ltm_data_group_defaults",
        ),
        TreeSpec(
            name="ltm_policies",
            active_dir=VARS_DIR / "ltm" / "policies",
            deletion_dir=VARS_DIR / "ltm" / "deletions" / "policies",
            top_key="ltm_policies",
            settings_key="ltm_policy_defaults",
        ),
        TreeSpec(
            name="gtm_monitors",
            active_dir=VARS_DIR / "gtm" / "monitors",
            deletion_dir=VARS_DIR / "gtm" / "deletions" / "monitors",
            top_key="gtm_monitors",
            settings_key="gtm_monitor_defaults",
        ),
        TreeSpec(
            name="gtm_datacenters",
            active_dir=VARS_DIR / "gtm" / "datacenters",
            deletion_dir=VARS_DIR / "gtm" / "deletions" / "datacenters",
            top_key="gtm_datacenters",
            settings_key="gtm_datacenter_defaults",
        ),
        TreeSpec(
            name="gtm_servers",
            active_dir=VARS_DIR / "gtm" / "servers",
            deletion_dir=VARS_DIR / "gtm" / "deletions" / "servers",
            top_key="gtm_servers",
            settings_key="gtm_server_defaults",
        ),
        TreeSpec(
            name="gtm_pools",
            active_dir=VARS_DIR / "gtm" / "pools",
            deletion_dir=VARS_DIR / "gtm" / "deletions" / "pools",
            top_key="gtm_pools",
            settings_key="gtm_pool_defaults",
            extra_settings_keys=("gtm_member_defaults", "gtm_monitor_sets"),
        ),
        TreeSpec(
            name="gtm_application_intents",
            active_dir=VARS_DIR / "gtm" / "intents" / "applications",
            deletion_dir=VARS_DIR / "gtm" / "deletions" / "intents" / "applications",
            top_key="gtm_application_intents",
            settings_key="gtm_application_intent_defaults",
            extra_settings_keys=("gtm_pool_defaults", "gtm_member_defaults", "gtm_monitor_sets"),
        ),
        TreeSpec(
            name="gtm_topology_regions",
            active_dir=VARS_DIR / "gtm" / "regions",
            deletion_dir=VARS_DIR / "gtm" / "deletions" / "regions",
            top_key="gtm_topology_regions",
            settings_key="gtm_topology_region_defaults",
        ),
        TreeSpec(
            name="gtm_topology_records",
            active_dir=VARS_DIR / "gtm" / "topology",
            deletion_dir=VARS_DIR / "gtm" / "deletions" / "topology",
            top_key="gtm_topology_records",
            settings_key="gtm_topology_record_defaults",
        ),
        TreeSpec(
            name="afm_address_lists",
            active_dir=VARS_DIR / "security" / "afm" / "address_lists",
            deletion_dir=VARS_DIR / "security" / "afm" / "deletions" / "address_lists",
            top_key="afm_address_lists",
            settings_key="afm_address_list_defaults",
        ),
        TreeSpec(
            name="afm_port_lists",
            active_dir=VARS_DIR / "security" / "afm" / "port_lists",
            deletion_dir=VARS_DIR / "security" / "afm" / "deletions" / "port_lists",
            top_key="afm_port_lists",
            settings_key="afm_port_list_defaults",
        ),
        TreeSpec(
            name="afm_rules",
            active_dir=VARS_DIR / "security" / "afm" / "rules",
            deletion_dir=VARS_DIR / "security" / "afm" / "deletions" / "rules",
            top_key="afm_rules",
            settings_key="afm_rule_defaults",
        ),
        TreeSpec(
            name="afm_policies",
            active_dir=VARS_DIR / "security" / "afm" / "policies",
            deletion_dir=VARS_DIR / "security" / "afm" / "deletions" / "policies",
            top_key="afm_policies",
            settings_key="afm_policy_defaults",
        ),
        TreeSpec(
            name="waf_policies",
            active_dir=VARS_DIR / "security" / "waf" / "policies",
            deletion_dir=VARS_DIR / "security" / "waf" / "deletions" / "policies",
            top_key="waf_policies",
            settings_key="waf_policy_defaults",
        ),
        TreeSpec(
            name="waf_server_technologies",
            active_dir=VARS_DIR / "security" / "waf" / "server_technologies",
            deletion_dir=VARS_DIR / "security" / "waf" / "deletions" / "server_technologies",
            top_key="waf_server_technologies",
            settings_key="waf_server_technology_defaults",
        ),
        TreeSpec(
            name="apm_acls",
            active_dir=VARS_DIR / "security" / "apm" / "acls",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "acls",
            top_key="apm_acls",
            settings_key="apm_acl_defaults",
        ),
        TreeSpec(
            name="apm_auth_servers",
            active_dir=VARS_DIR / "security" / "apm" / "auth_servers",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "auth_servers",
            top_key="apm_auth_servers",
            settings_key="apm_auth_server_defaults",
        ),
        TreeSpec(
            name="apm_sso_configs",
            active_dir=VARS_DIR / "security" / "apm" / "sso_configs",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "sso_configs",
            top_key="apm_sso_configs",
            settings_key="apm_sso_config_defaults",
        ),
        TreeSpec(
            name="apm_resources",
            active_dir=VARS_DIR / "security" / "apm" / "resources",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "resources",
            top_key="apm_resources",
            settings_key="apm_resource_defaults",
        ),
        TreeSpec(
            name="apm_policy_nodes",
            active_dir=VARS_DIR / "security" / "apm" / "policy_nodes",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "policy_nodes",
            top_key="apm_policy_nodes",
            settings_key="apm_policy_node_defaults",
        ),
        TreeSpec(
            name="apm_access_profiles",
            active_dir=VARS_DIR / "security" / "apm" / "access_profiles",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "access_profiles",
            top_key="apm_access_profiles",
            settings_key="apm_access_profile_defaults",
        ),
        TreeSpec(
            name="apm_per_session_policies",
            active_dir=VARS_DIR / "security" / "apm" / "per_session_policies",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "per_session_policies",
            top_key="apm_per_session_policies",
            settings_key="apm_per_session_policy_defaults",
        ),
        TreeSpec(
            name="apm_macros",
            active_dir=VARS_DIR / "security" / "apm" / "macros",
            deletion_dir=VARS_DIR / "security" / "apm" / "deletions" / "macros",
            top_key="apm_macros",
            settings_key="apm_macro_defaults",
        ),
    ]
