- name: Remove DNS settings
  f5networks.f5_modules.bigip_device_dns:
    provider: "{{ provider }}"
    name_servers: "{{ item.name_servers | default(omit) }}"
    search: "{{ item.search | default(omit) }}"
    cache: "{{ item.cache | default(omit) }}"
    ip_version: "{{ item.ip_version | default(omit) }}"
    state: absent
  loop: "{{ system_dns_delete | default([]) }}"
  loop_control:
    label: "{{ item.name_servers | default(item.search | default(['dns'])) | join(',') }}"

- name: Remove NTP settings
  f5networks.f5_modules.bigip_device_ntp:
    provider: "{{ provider }}"
    ntp_servers: "{{ item.ntp_servers | default(omit) }}"
    timezone: "{{ item.timezone | default(omit) }}"
    state: absent
  loop: "{{ system_ntp_delete | default([]) }}"
  loop_control:
    label: "{{ item.timezone | default(item.ntp_servers | default(['ntp']) | join(',')) }}"

- name: Deprovision BIG-IP modules
  f5networks.f5_modules.bigip_provision:
    provider: "{{ provider }}"
    module: "{{ item.module }}"
    memory: "{{ item.memory | default(omit) }}"
    state: absent
  loop: "{{ system_provisioning_delete | default([]) }}"
  loop_control:
    label: "{{ item.module }}"

- name: Remove local users
  f5networks.f5_modules.bigip_user:
    provider: "{{ provider }}"
    username_credential: "{{ item.name }}"
    partition: "{{ item.partition | default('Common') }}"
    state: absent
  loop: "{{ system_users_delete | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Remove RADIUS management-plane auth profile
  f5networks.f5_modules.bigip_device_auth_radius:
    provider: "{{ provider }}"
    state: absent
  loop: "{{ system_auth_radius_delete | default([]) }}"
  loop_control:
    label: "{{ item.name | default('radius-auth') }}"

- name: Remove RADIUS management-plane auth servers
  f5networks.f5_modules.bigip_device_auth_radius_server:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    partition: "{{ item.partition | default('Common') }}"
    state: absent
  loop: "{{ system_auth_radius_servers_delete | default([]) }}"
  loop_control:
    label: "{{ item.partition | default('Common') }}/{{ item.name }}"

- name: Remove TACACS management-plane auth providers
  f5networks.f5_modules.bigip_device_auth:
    provider: "{{ provider }}"
    type: tacacs
    state: absent
  loop: "{{ system_auth_tacacs_delete | default([]) }}"
  loop_control:
    label: "{{ item.name | default('tacacs-auth') }}"

- name: Remove LDAP management-plane auth providers
  f5networks.f5_modules.bigip_device_auth_ldap:
    provider: "{{ provider }}"
    name: "{{ item.name }}"
    state: absent
  loop: "{{ system_auth_ldap_delete | default([]) }}"
  loop_control:
    label: "{{ item.name }}"
