---
gtm_pools:
  - name: "pool_inventory_global"
    record_type: "a"
    preferred_lb_method: "topology"
    monitors:
      - "inventory_https"
    members:
      - server: "bigip-east"
        virtual_server: "vs_inventory_east_443"
      - server: "bigip-west"
        virtual_server: "vs_inventory_west_443"
        ltm_virtual_server: "vs_inventory_west_443"

  - name: "pool_reporting_global"
    record_type: "a"
    preferred_lb_method: "topology"
    monitors:
      - "reporting_https"
    members:
      - server: "bigip-east"
        virtual_server: "vs_reporting_east_443"
      - server: "bigip-west"
        virtual_server: "vs_reporting_west_443"
