#!/usr/bin/env python3

from __future__ import annotations

import sys
from dataclasses import dataclass
import ipaddress
from pathlib import Path
import re
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
VARS_DIR = ROOT / "vars"

from filter_plugins.bigip_var_filters import normalize_gtm_pool, normalize_ltm_pool


class AnsibleVarLoader(yaml.SafeLoader):
    pass


def construct_ansible_tag(loader: AnsibleVarLoader, tag_suffix: str, node: yaml.Node) -> Any:
    if isinstance(node, yaml.ScalarNode):
        return loader.construct_scalar(node)
    if isinstance(node, yaml.SequenceNode):
        return loader.construct_sequence(node)
    if isinstance(node, yaml.MappingNode):
        return loader.construct_mapping(node)
    raise TypeError(f"Unsupported YAML node type: {type(node)!r}")


AnsibleVarLoader.add_multi_constructor("!", construct_ansible_tag)


@dataclass(frozen=True)
class TreeSpec:
    name: str
    active_dir: Path
    deletion_dir: Path
    top_key: str
    settings_key: str
    extra_settings_keys: tuple[str, ...] = ()


@dataclass
class LoadedObject:
    tree: TreeSpec
    source_file: Path
    defaults: dict[str, Any]
    data: dict[str, Any]
    from_deletions: bool

    @property
    def relpath(self) -> str:
        return str(self.source_file.relative_to(ROOT))

    @property
    def effective_state(self) -> str:
        if self.from_deletions:
            return "absent"
        return str(self.data.get("state", "present"))

    @property
    def partition(self) -> str:
        return str(self.data.get("partition", self.defaults.get("partition", "Common")))


class Validator:
    def __init__(self) -> None:
        self.errors: list[str] = []
        self.objects: dict[str, list[LoadedObject]] = {}
        self.settings_cache: dict[Path, dict[str, Any]] = {}
        self.tree_specs = [
            TreeSpec(
                name="ha_device_trusts",
                active_dir=VARS_DIR / "ha" / "device_trust",
                deletion_dir=VARS_DIR / "ha" / "deletions" / "device_trust",
                top_key="ha_device_trusts",
                settings_key="ha_device_trust_defaults",
            ),
            TreeSpec(
                name="ha_device_groups",
                active_dir=VARS_DIR / "ha" / "device_groups",
                deletion_dir=VARS_DIR / "ha" / "deletions" / "device_groups",
                top_key="ha_device_groups",
                settings_key="ha_device_group_defaults",
            ),
            TreeSpec(
                name="ha_device_group_members",
                active_dir=VARS_DIR / "ha" / "device_group_members",
                deletion_dir=VARS_DIR / "ha" / "deletions" / "device_group_members",
                top_key="ha_device_group_members",
                settings_key="ha_device_group_member_defaults",
            ),
            TreeSpec(
                name="ha_traffic_groups",
                active_dir=VARS_DIR / "ha" / "traffic_groups",
                deletion_dir=VARS_DIR / "ha" / "deletions" / "traffic_groups",
                top_key="ha_traffic_groups",
                settings_key="ha_traffic_group_defaults",
            ),
            TreeSpec(
                name="ha_configsync_actions",
                active_dir=VARS_DIR / "ha" / "configsync_actions",
                deletion_dir=VARS_DIR / "ha" / "deletions" / "configsync_actions",
                top_key="ha_configsync_actions",
                settings_key="ha_configsync_action_defaults",
            ),
            TreeSpec(
                name="tls_keys",
                active_dir=VARS_DIR / "tls" / "keys",
                deletion_dir=VARS_DIR / "tls" / "deletions" / "keys",
                top_key="tls_keys",
                settings_key="tls_key_defaults",
            ),
            TreeSpec(
                name="tls_certificates",
                active_dir=VARS_DIR / "tls" / "certificates",
                deletion_dir=VARS_DIR / "tls" / "deletions" / "certificates",
                top_key="tls_certificates",
                settings_key="tls_certificate_defaults",
            ),
            TreeSpec(
                name="tls_ca_bundles",
                active_dir=VARS_DIR / "tls" / "ca_bundles",
                deletion_dir=VARS_DIR / "tls" / "deletions" / "ca_bundles",
                top_key="tls_ca_bundles",
                settings_key="tls_ca_bundle_defaults",
            ),
            TreeSpec(
                name="tls_client_ssl_profiles",
                active_dir=VARS_DIR / "tls" / "client_ssl_profiles",
                deletion_dir=VARS_DIR / "tls" / "deletions" / "client_ssl_profiles",
                top_key="tls_client_ssl_profiles",
                settings_key="tls_client_ssl_profile_defaults",
            ),
            TreeSpec(
                name="tls_server_ssl_profiles",
                active_dir=VARS_DIR / "tls" / "server_ssl_profiles",
                deletion_dir=VARS_DIR / "tls" / "deletions" / "server_ssl_profiles",
                top_key="tls_server_ssl_profiles",
                settings_key="tls_server_ssl_profile_defaults",
            ),
            TreeSpec(
                name="network_vlans",
                active_dir=VARS_DIR / "network" / "vlans",
                deletion_dir=VARS_DIR / "network" / "deletions" / "vlans",
                top_key="bigip_vlans",
                settings_key="network_vlan_defaults",
            ),
            TreeSpec(
                name="network_self_ips",
                active_dir=VARS_DIR / "network" / "self_ips",
                deletion_dir=VARS_DIR / "network" / "deletions" / "self_ips",
                top_key="bigip_self_ips",
                settings_key="network_self_ip_defaults",
            ),
            TreeSpec(
                name="network_route_domains",
                active_dir=VARS_DIR / "network" / "route_domains",
                deletion_dir=VARS_DIR / "network" / "deletions" / "route_domains",
                top_key="bigip_route_domains",
                settings_key="network_route_domain_defaults",
            ),
            TreeSpec(
                name="network_routes",
                active_dir=VARS_DIR / "network" / "routes",
                deletion_dir=VARS_DIR / "network" / "deletions" / "routes",
                top_key="bigip_static_routes",
                settings_key="network_route_defaults",
            ),
            TreeSpec(
                name="network_snat_translations",
                active_dir=VARS_DIR / "network" / "snat_translations",
                deletion_dir=VARS_DIR / "network" / "deletions" / "snat_translations",
                top_key="bigip_snat_translations",
                settings_key="network_snat_translation_defaults",
            ),
            TreeSpec(
                name="network_snat_pools",
                active_dir=VARS_DIR / "network" / "snats",
                deletion_dir=VARS_DIR / "network" / "deletions" / "snats",
                top_key="bigip_snat_pools",
                settings_key="network_snat_pool_defaults",
            ),
            TreeSpec(
                name="system_hostnames",
                active_dir=VARS_DIR / "system" / "hostname",
                deletion_dir=VARS_DIR / "system" / "deletions" / "hostname",
                top_key="system_hostnames",
                settings_key="system_hostname_defaults",
            ),
            TreeSpec(
                name="system_dns",
                active_dir=VARS_DIR / "system" / "dns",
                deletion_dir=VARS_DIR / "system" / "deletions" / "dns",
                top_key="system_dns",
                settings_key="system_dns_defaults",
            ),
            TreeSpec(
                name="system_ntp",
                active_dir=VARS_DIR / "system" / "ntp",
                deletion_dir=VARS_DIR / "system" / "deletions" / "ntp",
                top_key="system_ntp",
                settings_key="system_ntp_defaults",
            ),
            TreeSpec(
                name="system_provisioning",
                active_dir=VARS_DIR / "system" / "provisioning",
                deletion_dir=VARS_DIR / "system" / "deletions" / "provisioning",
                top_key="system_provisioning",
                settings_key="system_provisioning_defaults",
            ),
            TreeSpec(
                name="system_users",
                active_dir=VARS_DIR / "system" / "users",
                deletion_dir=VARS_DIR / "system" / "deletions" / "users",
                top_key="system_users",
                settings_key="system_user_defaults",
            ),
            TreeSpec(
                name="system_config",
                active_dir=VARS_DIR / "system" / "config",
                deletion_dir=VARS_DIR / "system" / "deletions" / "config",
                top_key="system_config",
                settings_key="system_config_defaults",
            ),
            TreeSpec(
                name="ltm_nodes",
                active_dir=VARS_DIR / "ltm" / "nodes",
                deletion_dir=VARS_DIR / "ltm" / "deletions" / "nodes",
                top_key="ltm_nodes",
                settings_key="ltm_node_defaults",
            ),
            TreeSpec(
                name="ltm_pools",
                active_dir=VARS_DIR / "ltm" / "pools",
                deletion_dir=VARS_DIR / "ltm" / "deletions" / "pools",
                top_key="ltm_pools",
                settings_key="ltm_pool_defaults",
                extra_settings_keys=("ltm_member_defaults", "ltm_monitor_sets"),
            ),
            TreeSpec(
                name="ltm_monitors",
                active_dir=VARS_DIR / "ltm" / "monitors",
                deletion_dir=VARS_DIR / "ltm" / "deletions" / "monitors",
                top_key="ltm_monitors",
                settings_key="ltm_monitor_defaults",
            ),
            TreeSpec(
                name="ltm_virtual_servers",
                active_dir=VARS_DIR / "ltm" / "virtual_servers",
                deletion_dir=VARS_DIR / "ltm" / "deletions" / "virtual_servers",
                top_key="ltm_virtual_servers",
                settings_key="ltm_virtual_server_defaults",
                extra_settings_keys=("ltm_pool_defaults", "ltm_member_defaults", "ltm_monitor_sets"),
            ),
            TreeSpec(
                name="gtm_monitors",
                active_dir=VARS_DIR / "gtm" / "monitors",
                deletion_dir=VARS_DIR / "gtm" / "deletions" / "monitors",
                top_key="gtm_monitors",
                settings_key="gtm_monitor_defaults",
            ),
            TreeSpec(
                name="gtm_datacenters",
                active_dir=VARS_DIR / "gtm" / "datacenters",
                deletion_dir=VARS_DIR / "gtm" / "deletions" / "datacenters",
                top_key="gtm_datacenters",
                settings_key="gtm_datacenter_defaults",
            ),
            TreeSpec(
                name="gtm_servers",
                active_dir=VARS_DIR / "gtm" / "servers",
                deletion_dir=VARS_DIR / "gtm" / "deletions" / "servers",
                top_key="gtm_servers",
                settings_key="gtm_server_defaults",
            ),
            TreeSpec(
                name="gtm_pools",
                active_dir=VARS_DIR / "gtm" / "pools",
                deletion_dir=VARS_DIR / "gtm" / "deletions" / "pools",
                top_key="gtm_pools",
                settings_key="gtm_pool_defaults",
                extra_settings_keys=("gtm_member_defaults", "gtm_monitor_sets"),
            ),
            TreeSpec(
                name="gtm_wide_ips",
                active_dir=VARS_DIR / "gtm" / "wide_ips",
                deletion_dir=VARS_DIR / "gtm" / "deletions" / "wide_ips",
                top_key="gtm_wide_ips",
                settings_key="gtm_wide_ip_defaults",
                extra_settings_keys=("gtm_pool_defaults", "gtm_member_defaults", "gtm_monitor_sets"),
            ),
        ]

    def run(self) -> int:
        self.validate_common()

        for spec in self.tree_specs:
            self.load_tree(spec, from_deletions=False)
            self.load_tree(spec, from_deletions=True)

        self.validate_network()
        self.validate_system()
        self.validate_ha()
        self.validate_tls()
        self.validate_ltm()
        self.validate_gtm()

        if self.errors:
            for error in self.errors:
                print(f"ERROR: {error}", file=sys.stderr)
            print(f"Validation failed with {len(self.errors)} error(s).", file=sys.stderr)
            return 1

        print("Validation passed.")
        return 0

    def validate_common(self) -> None:
        path = VARS_DIR / "common.yml"
        payload = self.load_yaml(path)
        if not isinstance(payload, dict):
            self.error(path, "must contain a mapping")
            return
        if "provider" not in payload:
            self.error(path, "must define `provider`")
        elif not isinstance(payload["provider"], dict):
            self.error(path, "`provider` must be a mapping")

    def load_tree(self, spec: TreeSpec, *, from_deletions: bool) -> None:
        base_dir = spec.deletion_dir if from_deletions else spec.active_dir
        if not base_dir.exists():
            return

        for path in sorted(base_dir.rglob("*.yml")):
            if path.name == "settings.yml":
                self.validate_settings_file(path, spec)
                continue

            payload = self.load_yaml(path)
            if not isinstance(payload, dict):
                self.error(path, "must contain a mapping")
                continue

            unknown = sorted(set(payload) - {spec.top_key})
            if unknown:
                self.error(path, f"contains unsupported keys: {', '.join(unknown)}")

            entries = payload.get(spec.top_key)
            if entries is None:
                self.error(path, f"must define `{spec.top_key}`")
                continue
            if not isinstance(entries, list):
                self.error(path, f"`{spec.top_key}` must be a list")
                continue

            defaults = self.load_directory_defaults(path.parent / "settings.yml", spec)
            for index, entry in enumerate(entries):
                if not isinstance(entry, dict):
                    self.error(path, f"`{spec.top_key}[{index}]` must be a mapping")
                    continue
                if from_deletions and "state" in entry and entry["state"] != "absent":
                    self.error(path, f"`{spec.top_key}[{index}]` in deletions may only use `state: absent`")
                self.objects.setdefault(spec.name, []).append(
                    LoadedObject(
                        tree=spec,
                        source_file=path,
                        defaults=defaults,
                        data=entry,
                        from_deletions=from_deletions,
                    )
                )

    def validate_settings_file(self, path: Path, spec: TreeSpec) -> None:
        payload = self.load_yaml(path)
        if not isinstance(payload, dict):
            self.error(path, "must contain a mapping")
            return

        allowed_keys = {spec.settings_key, *spec.extra_settings_keys}
        unknown = sorted(set(payload) - allowed_keys)
        if unknown:
            self.error(path, f"contains unsupported keys: {', '.join(unknown)}")

        defaults = payload.get(spec.settings_key)
        if defaults is not None and not isinstance(defaults, dict):
            self.error(path, f"`{spec.settings_key}` must be a mapping")

    def load_directory_defaults(self, path: Path, spec: TreeSpec) -> dict[str, Any]:
        if not path.exists():
            return {}
        payload = self.load_yaml(path)
        if not isinstance(payload, dict):
            return {}
        defaults = payload.get(spec.settings_key, {})
        return defaults if isinstance(defaults, dict) else {}

    def load_settings_payload(self, path: Path) -> dict[str, Any]:
        if path in self.settings_cache:
            return self.settings_cache[path]
        if not path.exists():
            self.settings_cache[path] = {}
            return {}
        payload = self.load_yaml(path)
        if not isinstance(payload, dict):
            self.settings_cache[path] = {}
            return {}
        self.settings_cache[path] = payload
        return payload

    def validate_network(self) -> None:
        vlans = self.objects.get("network_vlans", [])
        self_ips = self.objects.get("network_self_ips", [])
        route_domains = self.objects.get("network_route_domains", [])
        routes = self.objects.get("network_routes", [])
        snat_translations = self.objects.get("network_snat_translations", [])
        snat_pools = self.objects.get("network_snat_pools", [])

        active_vlan_names = set()

        for obj in vlans:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                active_vlan_names.add(self.fq_name(obj.partition, str(obj.data["name"])))
                interfaces = obj.data.get("interfaces")
                if interfaces is not None and not isinstance(interfaces, list):
                    self.error(obj.relpath, "`interfaces` must be a list")

        active_route_domain_ids = {0}

        for obj in route_domains:
            if obj.effective_state == "absent":
                continue
            route_domain_id = obj.data.get("id")
            if isinstance(route_domain_id, int):
                active_route_domain_ids.add(route_domain_id)

        for obj in route_domains:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue
            self.require_fields(obj, ["id"])
            route_domain_id = obj.data.get("id")
            if route_domain_id is not None:
                if not isinstance(route_domain_id, int):
                    self.error(obj.relpath, f"route domain `{obj.data.get('name')}` `id` must be an integer")
            vlans_list = obj.data.get("vlans")
            if vlans_list is not None and not isinstance(vlans_list, list):
                self.error(obj.relpath, f"route domain `{obj.data.get('name')}` `vlans` must be a list")
            for vlan in vlans_list or []:
                self.validate_named_or_fq_reference(
                    obj.relpath,
                    vlan,
                    obj.partition,
                    active_vlan_names,
                    "route domain VLAN",
                )
            routing_protocol = obj.data.get("routing_protocol")
            if routing_protocol is not None and not isinstance(routing_protocol, list):
                self.error(obj.relpath, f"route domain `{obj.data.get('name')}` `routing_protocol` must be a list")
            parent = obj.data.get("parent")
            if parent not in (None, ""):
                parent_id = self.normalize_route_domain_id(parent)
                if parent_id is None:
                    self.error(obj.relpath, f"route domain `{obj.data.get('name')}` `parent` must be an integer route domain ID")

        for obj in self_ips:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                self.require_fields(obj, ["address", "netmask", "vlan"])
                self.validate_named_or_fq_reference(
                    obj.relpath,
                    obj.data.get("vlan"),
                    obj.partition,
                    active_vlan_names,
                    "self IP VLAN",
                )
                route_domain_id = self.extract_route_domain_id(obj.data.get("address"))
                if route_domain_id is not None and route_domain_id not in active_route_domain_ids:
                    self.error(obj.relpath, f"self IP `{obj.data.get('name')}` references undefined route domain `{route_domain_id}` in `address`")

        active_snat_translation_names = set()

        for obj in snat_translations:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                self.require_fields(obj, ["address"])
                active_snat_translation_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        for obj in snat_pools:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue
            members = obj.data.get("members")
            if not isinstance(members, list) or not members:
                self.error(obj.relpath, f"SNAT pool `{obj.data.get('name')}` must define a non-empty `members` list")
                continue
            for member in members:
                if not isinstance(member, str):
                    self.error(obj.relpath, f"SNAT pool `{obj.data.get('name')}` member references must be strings")
                    continue
                if self.is_ip_address(member):
                    continue
                self.validate_named_or_fq_reference(
                    obj.relpath,
                    member,
                    obj.partition,
                    active_snat_translation_names,
                    "SNAT pool member",
                )

        for obj in routes:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue
            self.require_fields(obj, ["destination", "netmask"])
            if not any(obj.data.get(field) not in (None, "") for field in ("gateway_address", "pool")) and not bool(obj.data.get("reject")):
                self.error(obj.relpath, f"static route `{obj.data.get('name')}` must define `gateway_address`, `pool`, or `reject: true`")
            if obj.data.get("vlan") is not None:
                self.validate_named_or_fq_reference(
                    obj.relpath,
                    obj.data.get("vlan"),
                    obj.partition,
                    active_vlan_names,
                    "static route VLAN",
                )
            route_domain = obj.data.get("route_domain")
            if route_domain is not None:
                if not isinstance(route_domain, int):
                    self.error(obj.relpath, f"static route `{obj.data.get('name')}` `route_domain` must be an integer")
                elif route_domain not in active_route_domain_ids:
                    self.error(obj.relpath, f"static route `{obj.data.get('name')}` references undefined route domain `{route_domain}`")

        self.check_duplicates(vlans, lambda obj: ("vlan", obj.partition, obj.data.get("name")), "VLAN")
        self.check_duplicates(route_domains, lambda obj: ("route_domain", obj.partition, obj.data.get("name")), "route domain")
        self.check_duplicates(
            route_domains,
            lambda obj: ("route_domain_id", obj.data.get("id")),
            "route domain ID",
        )
        self.check_duplicates(self_ips, lambda obj: ("self_ip", obj.partition, obj.data.get("name")), "self IP")
        self.check_duplicates(routes, lambda obj: ("static_route", obj.partition, obj.data.get("name")), "static route")
        self.check_duplicates(
            snat_translations,
            lambda obj: ("snat_translation", obj.partition, obj.data.get("name")),
            "SNAT translation",
        )
        self.check_duplicates(snat_pools, lambda obj: ("snat_pool", obj.partition, obj.data.get("name")), "SNAT pool")

    def validate_system(self) -> None:
        hostnames = self.objects.get("system_hostnames", [])
        dns_settings = self.objects.get("system_dns", [])
        ntp_settings = self.objects.get("system_ntp", [])
        provisioning = self.objects.get("system_provisioning", [])
        users = self.objects.get("system_users", [])
        config = self.objects.get("system_config", [])

        for obj in hostnames:
            if obj.effective_state != "absent":
                self.require_fields(obj, ["hostname"])

        for obj in dns_settings:
            if obj.effective_state != "absent":
                if not obj.data.get("name_servers") and not obj.data.get("search") and obj.data.get("cache") is None and obj.data.get("ip_version") is None:
                    self.error(obj.relpath, "system DNS object must define at least one of `name_servers`, `search`, `cache`, or `ip_version`")

        for obj in ntp_settings:
            if obj.effective_state != "absent":
                if not obj.data.get("ntp_servers") and not obj.data.get("timezone"):
                    self.error(obj.relpath, "system NTP object must define `ntp_servers` or `timezone`")

        for obj in provisioning:
            self.require_fields(obj, ["module"])
            if obj.effective_state != "absent" and obj.data.get("module") != "mgmt" and not obj.data.get("level"):
                self.error(obj.relpath, f"system provisioning module `{obj.data.get('module')}` should define `level`")

        self.check_duplicates(
            provisioning,
            lambda obj: ("system_provisioning", obj.data.get("module")),
            "system provisioning module",
        )

        for obj in users:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                if obj.data.get("name") != "root" and not obj.data.get("partition_access"):
                    self.error(obj.relpath, f"system user `{obj.data.get('name')}` must define `partition_access`")
                if obj.data.get("state", "present") == "present" and obj.data.get("password_credential") is None and obj.data.get("update_password") == "on_create":
                    self.error(obj.relpath, f"system user `{obj.data.get('name')}` uses `update_password: on_create` without `password_credential`")

        self.check_duplicates(users, lambda obj: ("system_user", obj.data.get("name")), "system user")

        for obj in config:
            if "save" in obj.data and not isinstance(obj.data.get("save"), bool):
                self.error(obj.relpath, "`save` must be a boolean")

    def validate_ha(self) -> None:
        trusts = self.objects.get("ha_device_trusts", [])
        groups = self.objects.get("ha_device_groups", [])
        members = self.objects.get("ha_device_group_members", [])
        traffic_groups = self.objects.get("ha_traffic_groups", [])
        configsync_actions = self.objects.get("ha_configsync_actions", [])

        active_group_names = set()

        for obj in trusts:
            self.require_fields(obj, ["peer_server"])
            if obj.data.get("type") not in (None, "peer", "subordinate"):
                self.error(obj.relpath, f"HA device trust `{obj.data.get('peer_server')}` has unsupported `type`")

        self.check_duplicates(
            trusts,
            lambda obj: ("ha_device_trust", obj.data.get("peer_server"), obj.data.get("peer_hostname")),
            "HA device trust",
        )

        for obj in groups:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue
            active_group_names.add(str(obj.data["name"]))
            if obj.data.get("type") not in (None, "sync-failover", "sync-only"):
                self.error(obj.relpath, f"HA device group `{obj.data.get('name')}` has unsupported `type`")

        self.check_duplicates(groups, lambda obj: ("ha_device_group", obj.data.get("name")), "HA device group")

        for obj in members:
            self.require_fields(obj, ["device_group", "name"])
            if obj.effective_state != "absent" and str(obj.data["device_group"]) not in active_group_names:
                self.error(obj.relpath, f"HA device group member `{obj.data.get('name')}` references undefined device group `{obj.data.get('device_group')}`")

        self.check_duplicates(
            members,
            lambda obj: ("ha_device_group_member", obj.data.get("device_group"), obj.data.get("name")),
            "HA device group member",
        )

        for obj in traffic_groups:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue
            if obj.data.get("auto_failback_time") is not None and obj.data.get("auto_failback") is None:
                self.error(obj.relpath, f"HA traffic group `{obj.data.get('name')}` sets `auto_failback_time` without `auto_failback`")
            if obj.data.get("ha_group") not in (None, "") and obj.data.get("ha_order") not in (None, ""):
                self.error(obj.relpath, f"HA traffic group `{obj.data.get('name')}` cannot set both `ha_group` and `ha_order`")

        self.check_duplicates(
            traffic_groups,
            lambda obj: ("ha_traffic_group", obj.partition, obj.data.get("name")),
            "HA traffic group",
        )

        for obj in configsync_actions:
            self.require_fields(obj, ["device_group"])
            if obj.from_deletions:
                self.error(obj.relpath, "HA config sync actions do not support deletion trees")
            push = bool(obj.data.get("sync_device_to_group"))
            pull = bool(obj.data.get("sync_group_to_device"))
            if push == pull:
                self.error(obj.relpath, "HA config sync action must set exactly one of `sync_device_to_group` or `sync_group_to_device`")
            if str(obj.data.get("device_group")) not in active_group_names:
                self.error(obj.relpath, f"HA config sync action references undefined device group `{obj.data.get('device_group')}`")

    def validate_tls(self) -> None:
        keys = self.objects.get("tls_keys", [])
        certificates = self.objects.get("tls_certificates", [])
        ca_bundles = self.objects.get("tls_ca_bundles", [])
        client_ssl_profiles = self.objects.get("tls_client_ssl_profiles", [])
        server_ssl_profiles = self.objects.get("tls_server_ssl_profiles", [])

        active_key_names = set()
        active_certificate_names = set()
        active_ca_bundle_names = set()

        for obj in keys:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                self.require_fields(obj, ["content"])
                active_key_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        self.check_duplicates(keys, lambda obj: ("tls_key", obj.partition, obj.data.get("name")), "TLS key")

        for obj in certificates:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                self.require_fields(obj, ["content"])
                active_certificate_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        self.check_duplicates(certificates, lambda obj: ("tls_certificate", obj.partition, obj.data.get("name")), "TLS certificate")

        for obj in ca_bundles:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                self.require_fields(obj, ["content"])
                active_ca_bundle_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        self.check_duplicates(ca_bundles, lambda obj: ("tls_ca_bundle", obj.partition, obj.data.get("name")), "TLS CA bundle")

        known_cert_like_names = active_certificate_names | active_ca_bundle_names

        for obj in client_ssl_profiles:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue
            if obj.data.get("cert_key_chain") is not None and not isinstance(obj.data.get("cert_key_chain"), list):
                self.error(obj.relpath, f"TLS client SSL profile `{obj.data.get('name')}` `cert_key_chain` must be a list")
            for index, chain in enumerate(obj.data.get("cert_key_chain", []) or []):
                if not isinstance(chain, dict):
                    self.error(obj.relpath, f"TLS client SSL profile `{obj.data.get('name')}` cert_key_chain entry {index} must be a mapping")
                    continue
                self.require_fields(chain, ["cert", "key"], obj.relpath, f"TLS client SSL profile `{obj.data.get('name')}` cert_key_chain entry {index}")
                self.validate_named_or_fq_reference(obj.relpath, chain.get("cert"), obj.partition, active_certificate_names, "TLS client SSL certificate")
                self.validate_named_or_fq_reference(obj.relpath, chain.get("key"), obj.partition, active_key_names, "TLS client SSL key")
                if chain.get("chain") is not None:
                    self.validate_named_or_fq_reference(obj.relpath, chain.get("chain"), obj.partition, known_cert_like_names, "TLS client SSL chain")
            if obj.data.get("trusted_cert_authority") is not None:
                self.validate_fq_or_common_reference(obj.relpath, obj.data.get("trusted_cert_authority"), known_cert_like_names, "TLS trusted cert authority")
            if obj.data.get("advertised_cert_authority") is not None:
                self.validate_fq_or_common_reference(obj.relpath, obj.data.get("advertised_cert_authority"), known_cert_like_names, "TLS advertised cert authority")
            if obj.data.get("client_auth_crl") is not None and not isinstance(obj.data.get("client_auth_crl"), str):
                self.error(obj.relpath, f"TLS client SSL profile `{obj.data.get('name')}` `client_auth_crl` must be a string")

        self.check_duplicates(
            client_ssl_profiles,
            lambda obj: ("tls_client_ssl_profile", obj.partition, obj.data.get("name")),
            "TLS client SSL profile",
        )

        for obj in server_ssl_profiles:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue
            if obj.data.get("certificate") is not None:
                self.validate_named_or_fq_reference(obj.relpath, obj.data.get("certificate"), obj.partition, active_certificate_names, "TLS server SSL certificate")
            if obj.data.get("key") is not None:
                self.validate_named_or_fq_reference(obj.relpath, obj.data.get("key"), obj.partition, active_key_names, "TLS server SSL key")
            if obj.data.get("chain") is not None:
                self.validate_named_or_fq_reference(obj.relpath, obj.data.get("chain"), obj.partition, known_cert_like_names, "TLS server SSL chain")
            if obj.data.get("ca_file") is not None:
                self.validate_fq_or_common_reference(obj.relpath, obj.data.get("ca_file"), known_cert_like_names, "TLS server SSL CA file")

        self.check_duplicates(
            server_ssl_profiles,
            lambda obj: ("tls_server_ssl_profile", obj.partition, obj.data.get("name")),
            "TLS server SSL profile",
        )

    def validate_ltm(self) -> None:
        nodes = self.objects.get("ltm_nodes", [])
        pools = self.objects.get("ltm_pools", [])
        monitors = self.objects.get("ltm_monitors", [])
        virtual_servers = self.objects.get("ltm_virtual_servers", [])

        active_node_names = set()
        for obj in nodes:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                if not obj.data.get("address") and not obj.data.get("fqdn"):
                    self.error(obj.relpath, f"LTM node `{obj.data.get('name')}` must define either `address` or `fqdn`")
                active_node_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        self.check_duplicates(nodes, lambda obj: ("ltm_node", obj.partition, obj.data.get("name")), "LTM node")

        active_monitor_names = set()
        for obj in monitors:
            self.require_fields(obj, ["name", "type"])
            active = obj.effective_state != "absent"
            if active:
                active_monitor_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        self.check_duplicates(monitors, lambda obj: ("ltm_monitor", obj.partition, obj.data.get("name")), "LTM monitor")

        active_pool_names = set()

        for obj in pools:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue

            settings_payload = self.load_settings_payload(obj.source_file.parent / "settings.yml")
            normalized_pool = normalize_ltm_pool(
                obj.data,
                settings_payload.get("ltm_pool_defaults", {}),
                settings_payload.get("ltm_member_defaults", {}),
                settings_payload.get("ltm_monitor_sets", {}),
            )

            active_pool_names.add(self.fq_name(obj.partition, str(normalized_pool["name"])))

            monitors_list = normalized_pool.get("monitors", [])
            if monitors_list is not None and not isinstance(monitors_list, list):
                self.error(obj.relpath, f"LTM pool `{normalized_pool.get('name')}` `monitors` must be a list")
            else:
                for monitor in monitors_list or []:
                    self.validate_monitor_reference(
                        source=obj.relpath,
                        reference=monitor,
                        known_monitors=active_monitor_names,
                        kind="LTM pool monitor",
                    )

            self.validate_ltm_pool_members(obj.relpath, normalized_pool.get("name"), obj.partition, normalized_pool.get("members"), active_node_names)

        self.check_duplicates(pools, lambda obj: ("ltm_pool", obj.partition, obj.data.get("name")), "LTM pool")

        for obj in virtual_servers:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue

            self.require_fields(obj, ["destination", "destination_port", "pool"])
            pool = obj.data.get("pool")
            if isinstance(pool, str):
                pool_ref = self.normalize_pool_reference(pool, obj.partition)
                if pool_ref not in active_pool_names:
                    self.error(obj.relpath, f"virtual server `{obj.data.get('name')}` references undefined pool `{pool_ref}`")
                continue
            if not isinstance(pool, dict):
                self.error(obj.relpath, f"virtual server `{obj.data.get('name')}` pool must be a string reference or embedded pool mapping")
                continue

            if not pool.get("name"):
                self.error(obj.relpath, f"virtual server `{obj.data.get('name')}` embedded pool must define `name`")
                continue

            settings_payload = self.load_settings_payload(obj.source_file.parent / "settings.yml")
            normalized_pool = normalize_ltm_pool(
                pool,
                settings_payload.get("ltm_pool_defaults", {}),
                settings_payload.get("ltm_member_defaults", {}),
                settings_payload.get("ltm_monitor_sets", {}),
            )

            pool_partition = str(normalized_pool.get("partition", obj.partition))
            active_pool_names.add(self.fq_name(pool_partition, str(normalized_pool["name"])))

            monitors_list = normalized_pool.get("monitors", [])
            if monitors_list is not None and not isinstance(monitors_list, list):
                self.error(obj.relpath, f"LTM pool `{normalized_pool.get('name')}` `monitors` must be a list")
            else:
                for monitor in monitors_list or []:
                    self.validate_monitor_reference(
                        source=obj.relpath,
                        reference=monitor,
                        known_monitors=active_monitor_names,
                        kind="LTM pool monitor",
                    )

            self.validate_ltm_pool_members(
                obj.relpath,
                normalized_pool.get("name"),
                pool_partition,
                normalized_pool.get("members"),
                active_node_names,
            )

        self.check_duplicates(
            virtual_servers,
            lambda obj: ("ltm_virtual_server", obj.partition, obj.data.get("name")),
            "LTM virtual server",
        )

    def validate_ltm_pool_members(
        self,
        source: str,
        pool_name: Any,
        pool_partition: str,
        members: Any,
        active_node_names: set[str],
    ) -> None:
        if members is None:
            return
        if not isinstance(members, list):
            self.error(source, f"LTM pool `{pool_name}` members must be a list")
            return

        for idx, member in enumerate(members):
            if not isinstance(member, dict):
                self.error(source, f"LTM pool `{pool_name}` member {idx} must be a mapping")
                continue
            self.require_fields(member, ["port"], source, f"LTM pool `{pool_name}` member {idx}")
            if not member.get("host") and not member.get("address") and not member.get("fqdn"):
                self.error(source, f"LTM pool `{pool_name}` member {idx} must define one of `host`, `address`, or `fqdn`")
            member_name = member.get("name")
            if member_name:
                fq_node = self.fq_name(str(member.get("partition", pool_partition)), str(member_name))
                if fq_node not in active_node_names:
                    self.error(source, f"LTM pool `{pool_name}` member `{member_name}` references undefined node `{fq_node}`")

    def validate_gtm(self) -> None:
        datacenters = self.objects.get("gtm_datacenters", [])
        monitors = self.objects.get("gtm_monitors", [])
        servers = self.objects.get("gtm_servers", [])
        pools = self.objects.get("gtm_pools", [])
        wide_ips = self.objects.get("gtm_wide_ips", [])
        ltm_virtual_servers = self.objects.get("ltm_virtual_servers", [])

        active_datacenter_names = set()
        for obj in datacenters:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                active_datacenter_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        for obj in servers:
            if obj.effective_state != "absent" and obj.data.get("datacenter"):
                active_datacenter_names.add(self.fq_name(obj.partition, str(obj.data["datacenter"])))

        self.check_duplicates(datacenters, lambda obj: ("gtm_datacenter", obj.partition, obj.data.get("name")), "GTM datacenter")

        active_monitor_names = set()
        for obj in monitors:
            self.require_fields(obj, ["name", "type"])
            if obj.effective_state != "absent":
                active_monitor_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        self.check_duplicates(monitors, lambda obj: ("gtm_monitor", obj.partition, obj.data.get("name")), "GTM monitor")

        active_server_names = set()
        for obj in servers:
            self.require_fields(obj, ["name"])
            if obj.effective_state != "absent":
                self.require_fields(obj, ["datacenter"])
                if not obj.data.get("address") and not obj.data.get("devices"):
                    self.error(obj.relpath, f"GTM server `{obj.data.get('name')}` must define `address` or `devices`")
                fq_datacenter = self.fq_name(obj.partition, str(obj.data["datacenter"]))
                if fq_datacenter not in active_datacenter_names:
                    self.error(obj.relpath, f"GTM server `{obj.data.get('name')}` references undefined datacenter `{fq_datacenter}`")
                active_server_names.add(self.fq_name(obj.partition, str(obj.data["name"])))

        self.check_duplicates(servers, lambda obj: ("gtm_server", obj.partition, obj.data.get("name")), "GTM server")

        active_pool_names = set()
        active_ltm_virtual_servers = self.build_ltm_virtual_server_lookup(ltm_virtual_servers)

        for obj in pools:
            self.require_fields(obj, ["name"])
            if obj.effective_state == "absent":
                continue

            settings_payload = self.load_settings_payload(obj.source_file.parent / "settings.yml")
            normalized_pool = normalize_gtm_pool(
                obj.data,
                settings_payload.get("gtm_pool_defaults", {}),
                settings_payload.get("gtm_member_defaults", {}),
                settings_payload.get("gtm_monitor_sets", {}),
                active_ltm_virtual_servers,
            )

            record_type = str(normalized_pool.get("record_type", "a"))
            active_pool_names.add(self.fq_gtm_pool_name(obj.partition, record_type, str(normalized_pool["name"])))

            for monitor in normalized_pool.get("monitors", normalized_pool.get("default_monitors", [])) or []:
                self.validate_monitor_reference(
                    source=obj.relpath,
                    reference=monitor,
                    known_monitors=active_monitor_names,
                    kind="GTM pool monitor",
                )

            self.validate_gtm_pool_members(
                source=obj.relpath,
                pool_name=normalized_pool.get("name"),
                pool_partition=obj.partition,
                members=normalized_pool.get("members"),
                active_server_names=active_server_names,
                active_monitor_names=active_monitor_names,
                active_ltm_virtual_servers=active_ltm_virtual_servers,
            )

        self.check_duplicates(
            pools,
            lambda obj: ("gtm_pool", obj.partition, obj.data.get("name"), obj.data.get("record_type", "a")),
            "GTM pool",
        )

        for obj in wide_ips:
            self.require_fields(obj, ["name"])
            record_type = str(obj.data.get("record_type", "a"))
            if obj.effective_state == "absent":
                continue

            pools = obj.data.get("pools")
            if pools is None or not isinstance(pools, list) or not pools:
                self.error(obj.relpath, f"GTM Wide IP `{obj.data.get('name')}` must define a non-empty `pools` list")
                continue

            for pool_index, pool in enumerate(pools):
                if isinstance(pool, str):
                    pool_ref = self.normalize_gtm_pool_reference(pool, obj.partition, record_type)
                    if pool_ref not in active_pool_names:
                        self.error(obj.relpath, f"GTM Wide IP `{obj.data.get('name')}` references undefined pool `{pool_ref}`")
                    continue

                if not isinstance(pool, dict):
                    self.error(obj.relpath, f"GTM Wide IP `{obj.data.get('name')}` pool {pool_index} must be a string or mapping")
                    continue
                if "name" not in pool:
                    self.error(obj.relpath, f"GTM Wide IP `{obj.data.get('name')}` pool {pool_index} must define `name`")
                    continue

                pool_partition = str(pool.get("partition", obj.partition))
                if self.is_inline_gtm_pool(pool):
                    settings_payload = self.load_settings_payload(obj.source_file.parent / "settings.yml")
                    normalized_pool = normalize_gtm_pool(
                        pool,
                        settings_payload.get("gtm_pool_defaults", {}),
                        settings_payload.get("gtm_member_defaults", {}),
                        settings_payload.get("gtm_monitor_sets", {}),
                        active_ltm_virtual_servers,
                    )
                    pool_partition = str(normalized_pool.get("partition", obj.partition))
                    active_pool_names.add(self.fq_gtm_pool_name(pool_partition, record_type, str(normalized_pool["name"])))
                    for monitor in normalized_pool.get("monitors", normalized_pool.get("default_monitors", [])) or []:
                        self.validate_monitor_reference(
                            source=obj.relpath,
                            reference=monitor,
                            known_monitors=active_monitor_names,
                            kind="GTM pool monitor",
                        )
                    self.validate_gtm_pool_members(
                        source=obj.relpath,
                        pool_name=normalized_pool.get("name"),
                        pool_partition=pool_partition,
                        members=normalized_pool.get("members"),
                        active_server_names=active_server_names,
                        active_monitor_names=active_monitor_names,
                        active_ltm_virtual_servers=active_ltm_virtual_servers,
                    )
                    continue

                unsupported = sorted(set(pool) - {"name", "partition", "ratio"})
                if unsupported:
                    self.error(obj.relpath, f"GTM Wide IP `{obj.data.get('name')}` pool reference `{pool.get('name')}` contains unsupported keys: {', '.join(unsupported)}")
                pool_ref = self.fq_gtm_pool_name(pool_partition, record_type, str(pool["name"]))
                if pool_ref not in active_pool_names:
                    self.error(obj.relpath, f"GTM Wide IP `{obj.data.get('name')}` references undefined pool `{pool_ref}`")

        self.check_duplicates(
            wide_ips,
            lambda obj: ("gtm_wide_ip", obj.partition, obj.data.get("name"), obj.data.get("record_type", "a")),
            "GTM Wide IP",
        )

    def validate_gtm_pool_members(
        self,
        *,
        source: str,
        pool_name: Any,
        pool_partition: str,
        members: Any,
        active_server_names: set[str],
        active_monitor_names: set[str],
        active_ltm_virtual_servers: dict[str, dict[str, Any]],
    ) -> None:
        if members is None:
            return
        if not isinstance(members, list):
            self.error(source, f"GTM pool `{pool_name}` members must be a list")
            return
        if not members:
            self.error(source, f"GTM pool `{pool_name}` must define a non-empty `members` list")
            return

        for member_index, member in enumerate(members):
            if not isinstance(member, dict):
                self.error(source, f"GTM pool `{pool_name}` member {member_index} must be a mapping")
                continue
            self.require_fields(member, ["server", "virtual_server"], source, f"GTM member {member_index}")
            self.validate_gtm_member_ltm_reference(
                source=source,
                pool_name=pool_name,
                member_index=member_index,
                pool_partition=pool_partition,
                member=member,
                active_ltm_virtual_servers=active_ltm_virtual_servers,
            )
            if member.get("state") != "absent":
                self.require_fields(member, ["address", "port"], source, f"GTM member {member_index}")
            server_partition = str(member.get("partition", pool_partition))
            server_name = member.get("server")
            if server_name is not None:
                fq_server = self.fq_name(server_partition, str(server_name))
                if fq_server not in active_server_names:
                    self.error(source, f"GTM member `{server_name}` references undefined server `{fq_server}`")
            for monitor in member.get("monitors", []) or []:
                self.validate_monitor_reference(
                    source=source,
                    reference=monitor,
                    known_monitors=active_monitor_names,
                    kind="GTM member monitor",
                )

    def validate_gtm_member_ltm_reference(
        self,
        *,
        source: str,
        pool_name: Any,
        member_index: int,
        pool_partition: str,
        member: dict[str, Any],
        active_ltm_virtual_servers: dict[str, dict[str, Any]],
    ) -> None:
        if member.get("address") not in (None, "") and member.get("port") not in (None, ""):
            return

        ltm_name = member.get("ltm_virtual_server", member.get("virtual_server"))
        if ltm_name in (None, ""):
            return

        ltm_partition = str(member.get("ltm_partition", member.get("partition", pool_partition)))
        fq_ltm_virtual = ltm_name if isinstance(ltm_name, str) and ltm_name.startswith("/") else self.fq_name(ltm_partition, str(ltm_name))
        if fq_ltm_virtual not in active_ltm_virtual_servers:
            self.error(
                source,
                f"GTM pool `{pool_name}` member {member_index} cannot resolve repo-known LTM virtual `{fq_ltm_virtual}`",
            )

    def build_ltm_virtual_server_lookup(self, virtual_servers: list[LoadedObject]) -> dict[str, dict[str, Any]]:
        lookup: dict[str, dict[str, Any]] = {}
        for obj in virtual_servers:
            if obj.effective_state == "absent":
                continue
            name = obj.data.get("name")
            destination = obj.data.get("destination")
            destination_port = obj.data.get("destination_port")
            if name in (None, "") or destination in (None, "") or destination_port in (None, ""):
                continue
            lookup[self.fq_name(obj.partition, str(name))] = {
                "destination": destination,
                "destination_port": destination_port,
            }
        return lookup

    def validate_monitor_reference(
        self,
        *,
        source: str,
        reference: Any,
        known_monitors: set[str],
        kind: str,
    ) -> None:
        if not isinstance(reference, str):
            self.error(source, f"{kind} reference must be a string")
            return
        if not reference.startswith("/"):
            self.error(source, f"{kind} reference `{reference}` must be fully qualified, for example `/Common/name`")
            return
        partition, _, name = reference.strip("/").partition("/")
        if not partition or not name:
            self.error(source, f"{kind} reference `{reference}` is not a valid fully-qualified object name")
            return
        if partition != "Common" and reference not in known_monitors:
            self.error(source, f"{kind} reference `{reference}` does not match a declared custom monitor")
        if partition == "Common" and reference in known_monitors:
            return

    def validate_named_or_fq_reference(
        self,
        source: str,
        reference: Any,
        default_partition: str,
        known_objects: set[str],
        kind: str,
    ) -> None:
        if not isinstance(reference, str):
            self.error(source, f"{kind} reference must be a string")
            return
        fq_reference = reference if reference.startswith("/") else self.fq_name(default_partition, reference)
        if fq_reference not in known_objects:
            self.error(source, f"{kind} reference `{reference}` does not match a declared object")

    def validate_fq_or_common_reference(
        self,
        source: str,
        reference: Any,
        known_objects: set[str],
        kind: str,
    ) -> None:
        if not isinstance(reference, str):
            self.error(source, f"{kind} reference must be a string")
            return
        if not reference.startswith("/"):
            self.error(source, f"{kind} reference `{reference}` must be fully qualified, for example `/Common/name`")
            return
        if reference.startswith("/Common/") and reference not in known_objects:
            return
        if reference not in known_objects:
            self.error(source, f"{kind} reference `{reference}` does not match a declared object")

    def check_duplicates(
        self,
        objects: list[LoadedObject],
        key_func,
        label: str,
    ) -> None:
        seen: dict[tuple[Any, ...], LoadedObject] = {}
        for obj in objects:
            key = key_func(obj)
            if any(part is None for part in key):
                continue
            if key in seen:
                self.error(obj.relpath, f"{label} `{key[1:]}` duplicates {seen[key].relpath}")
            else:
                seen[key] = obj

    def require_fields(
        self,
        obj: LoadedObject | dict[str, Any],
        fields: list[str],
        source: str | None = None,
        label: str | None = None,
    ) -> None:
        data = obj.data if isinstance(obj, LoadedObject) else obj
        source_ref = obj.relpath if isinstance(obj, LoadedObject) else (source or "<unknown>")
        prefix = label or "object"
        for field in fields:
            if data.get(field) in (None, ""):
                self.error(source_ref, f"{prefix} must define `{field}`")

    def fq_name(self, partition: str, name: str) -> str:
        return f"/{partition}/{name}"

    def normalize_pool_reference(self, reference: str, default_partition: str) -> str:
        if reference.startswith("/"):
            return reference
        return self.fq_name(default_partition, reference)

    def fq_gtm_pool_name(self, partition: str, record_type: str, name: str) -> str:
        return f"/{partition}/{record_type}/{name}"

    def normalize_gtm_pool_reference(self, reference: str, default_partition: str, record_type: str) -> str:
        if reference.startswith("/"):
            parts = reference.strip("/").split("/", 2)
            if len(parts) == 3:
                return reference
            if len(parts) == 2:
                return f"/{parts[0]}/{record_type}/{parts[1]}"
            return f"/{default_partition}/{record_type}/{reference.strip('/')}"
        return self.fq_gtm_pool_name(default_partition, record_type, reference)

    def is_inline_gtm_pool(self, pool: dict[str, Any]) -> bool:
        return "members" in pool or "monitors" in pool or "default_monitors" in pool

    def load_yaml(self, path: Path) -> Any:
        try:
            with path.open("r", encoding="utf-8") as handle:
                return yaml.load(handle, Loader=AnsibleVarLoader) or {}
        except yaml.YAMLError as exc:
            self.error(path, f"failed to parse YAML: {exc}")
            return {}
        except OSError as exc:
            self.error(path, f"failed to read file: {exc}")
            return {}

    def error(self, source: Path | str, message: str) -> None:
        rel = str(source.relative_to(ROOT)) if isinstance(source, Path) else source
        self.errors.append(f"{rel}: {message}")

    def normalize_route_domain_id(self, value: Any) -> int | None:
        if isinstance(value, int):
            return value
        if isinstance(value, str) and value.isdigit():
            return int(value)
        return None

    def extract_route_domain_id(self, value: Any) -> int | None:
        if not isinstance(value, str):
            return None
        match = re.search(r"%(\d+)$", value)
        if match is None:
            return None
        return int(match.group(1))

    def is_ip_address(self, value: str) -> bool:
        try:
            ipaddress.ip_address(value)
        except ValueError:
            return False
        return True


def main() -> int:
    return Validator().run()


if __name__ == "__main__":
    raise SystemExit(main())
