---
- name: Configure BIG-IP HA objects
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars:
    repo_root: "{{ playbook_dir }}/.."

  vars_files:
    - "{{ repo_root }}/vars/common.yml"

  pre_tasks:
    - name: Prepare HA inputs
      ansible.builtin.import_tasks: ha/prep.yml

  tasks:
    - name: Manage HA objects
      ansible.builtin.import_tasks: ha/tasks/manage.yml
