---
- name: Configure BIG-IP LTM objects
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars:
    repo_root: "{{ playbook_dir }}/.."

  vars_files:
    - "{{ repo_root }}/vars/common.yml"

  pre_tasks:
    - name: Prepare LTM inputs
      ansible.builtin.import_tasks: ltm/prep.yml

  tasks:
    - name: Manage LTM objects
      ansible.builtin.import_tasks: ltm/tasks/manage.yml
