---
- name: Configure BIG-IP base system settings
  hosts: localhost
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars:
    repo_root: "{{ playbook_dir }}/.."

  vars_files:
    - "{{ repo_root }}/vars/common.yml"

  pre_tasks:
    - name: Prepare system inputs
      ansible.builtin.import_tasks: system/prep.yml

  tasks:
    - name: Manage system objects
      ansible.builtin.import_tasks: system/tasks/manage.yml
