---
- name: Configure BIG-IP TLS objects
  hosts: localhost
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars:
    repo_root: "{{ playbook_dir }}/.."

  vars_files:
    - "{{ repo_root }}/vars/common.yml"

  pre_tasks:
    - name: Prepare TLS inputs
      ansible.builtin.import_tasks: tls/prep.yml

  tasks:
    - name: Manage TLS objects
      ansible.builtin.import_tasks: tls/tasks/manage.yml
